# -*- coding: utf-8 -*-
"""KNN Assignment glass.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_LqbSN1WnmcNjk_wuXltiQLOk6WK4Tkz
"""

from google.colab import drive

drive.mount('/content/drive/')

cd drive/MyDrive/Assignments

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import *
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

"""Problem 1"""

data=pd.read_csv("glass.csv")
data

data=data.drop_duplicates()
data

scaler=StandardScaler()
x=scaler.fit_transform(data.iloc[:,:-1])
y=data.iloc[:,-1]

#Splitting data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=20,random_state=10)

#Creating Model
model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)

#Doing prediction
pred=model.predict(x_test)

#Creating classification report
print(classification_report(y_test,pred))

data["Type"].value_counts()

l=[]
for k in range(1,40,2):
  model=KNeighborsClassifier(n_neighbors=k)
  model.fit(x_train,y_train)
  pred=model.predict(x_test)
  l.append(accuracy_score(y_test,pred))

# plt.figure(figsize=(5,5))
plt.bar(range(1,40,2),l)
plt.plot(range(1,40,2),l)
plt.ylim(0,1)
plt.xticks(range(1,40,2))
plt.xlabel("K Values")
plt.ylabel("Accuracy")
plt.show

print("Accuracy", accuracy_score(y_test,pred)*100)