# -*- coding: utf-8 -*-
"""KNN Assignment Zoo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TKSC1z4S5IgzhEpCPb9UCft2aYA9C33F
"""

from google.colab import drive

drive.mount('/content/drive/')

cd drive/MyDrive/Assignments

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import *
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

data=pd.read_csv("Zoo.csv")
data

data=data.drop("animal name",axis=1)

scaler=StandardScaler()
x=scaler.fit_transform(data.iloc[:,:-1])
y=data.iloc[:,-1]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=20,random_state=10)

model=KNeighborsClassifier()
model.fit(x_train,y_train)

pred=model.predict(x_test)
print(classification_report(y_test,pred))

data["type"].value_counts()

l=[]
for i in range(1,20,2):
  model=KNeighborsClassifier(n_neighbors=i)
  model.fit(x_train,y_train)
  pred=model.predict(x_test)
  l.append(accuracy_score(y_test,pred))

plt.bar(range(1,20,2),l)
plt.plot(range(1,20,2),l)
plt.xlabel("K Values")
plt.ylabel("Accuracy")
plt.show

print("Accuracy",accuracy_score(y_test,pred)*100)

